apps/user_account/urls.py
from django.urls import path, include
from apps.user_account import views
from django.contrib.auth import views as auth_views

app_name = 'user_account'


reset_change_urls = [
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('pass_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('pass_reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('account-activate/<uid>/<token>/', views.AccountActivate.as_view(), name='activate'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('home/', views.Home.as_view(), name='home'),
    path('test-onclick/', views.test.as_view(), name='test'),
    path('user/', include(reset_change_urls)),
]

zipcodeit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social'), ),
    path('', include('apps.user_account.urls')),
    path('', include('apps.business_account.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/user_account/models.py
from django.db import models
from django.contrib.auth import models as auth_models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.mail import send_mail

GENDER_CHOICES = (
    ('M', _('Male')),
    ('F', _('Female')),
    ('O', _("Rather won't say")),
)


class UserManager(auth_models.BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(auth_models.AbstractBaseUser, auth_models.PermissionsMixin):
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last Name '), max_length=150)
    email = models.EmailField(_('email'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    dob = models.DateField(_('date of birth'), null=True)
    gender = models.CharField(verbose_name=_('gender'), max_length=20, choices=GENDER_CHOICES, null=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    avatar = models.ImageField(_('profile picture'), blank=True, null=True)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

apps/user_account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from apps.user_account.ajax_mixin import DictErrorMixin
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox, ReCaptchaV2Invisible, ReCaptchaV3


class CustomUserCreation(DictErrorMixin, UserCreationForm):
    # captcha = ReCaptchaField()

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2', 'avatar',
                  # 'dob', 'gender', 'captcha'
                  ]
        labels = {
            'password1': _('Password'),
            'password2': _('Password Again')
        }
        widgets = {
            'gender': forms.RadioSelect
        }


class LoginForm(DictErrorMixin, AuthenticationForm):
    pass

apps/user_account/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import views as auth_views
from django.views import generic
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils.translation import gettext_lazy as _
from django.shortcuts import render
from django.conf import settings

from apps.user_account.forms import LoginForm
from apps.user_account.ajax_mixin import AjaxResponseMixin
from apps.user_account.forms import CustomUserCreation


class SignupMixin(object):
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_active = False
        self.object.save()
        response = HttpResponseRedirect(self.get_success_url())
        current_site = get_current_site(self.request)
        email_subject = 'Activate Your ZIPCODEIT Account'
        token_generator = PasswordResetTokenGenerator()
        message = render_to_string('account_activation_email.html', {
            'user': self.object,
            'request': self.request,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(self.object.pk)).decode(),
            'token': token_generator.make_token(self.object),
        })
        self.object.email_user(email_subject, message, getattr(settings, 'EMAIL_HOST_USER', None))
        return response

    def form_invalid(self, form):
        print('Form Invalid')
        return super().form_invalid(form)


class SignupView(AjaxResponseMixin, SignupMixin, generic.CreateView):
    model = get_user_model()
    template_name = 'login.html'
    form_class = CustomUserCreation
    success_url = reverse_lazy('user_account:login')
    form_context_name = 'signup_form'
    success_messge = _('Signup Successful')

    def get_context_data(self, **kwargs):
        if self.form_context_name not in kwargs:
            kwargs[self.form_context_name] = self.get_form()
        return super().get_context_data(**kwargs)


class AccountActivate(generic.TemplateView):
    template_name = 'home.html'
    error_message = _('This link is invalid or this link has been used earlier')
    success_message = _('Your account has been activated successfully')

    def get(self, request, *args, **kwargs):
        uid = kwargs.get('uid')
        token = kwargs.get('token')
        try:
            user_pk = urlsafe_base64_decode(uid).decode()
        except (TypeError, ValueError, OverflowError):
            user_pk = None
        user_class = get_user_model()
        user = user_class.objects.filter(pk=user_pk)
        token_generator = PasswordResetTokenGenerator()
        context = {'message': self.error_message}
        if user.exists():
            if token_generator.check_token(user[0], token):
                user[0].is_active = True
                user[0].save()
                context = {
                    'activation_message': self.success_message
                }
        return render(request, self.template_name, context)


class LoginView(AjaxResponseMixin, auth_views.LoginView):
    template_name = 'login.html'
    success_url = reverse_lazy('user_account:home')
    form_context_name = 'login_form'
    form_class = LoginForm
    success_message = _('Login Successful')

    def get_context_data(self, **kwargs):
        if self.form_context_name not in kwargs:
            kwargs[self.form_context_name] = self.get_form()
        return super().get_context_data(**kwargs)


class Home(generic.TemplateView):
    template_name = 'home.html'


class test(generic.TemplateView):
    template_name = 'test.html'

apps/user_account/templates/account_activation_email.html
{% load i18n %}

{% autoescape off %}
{% trans 'Hi' %} {{ user.username }},
{% blocktrans %}
Please click on the link below to confirm your registration on zipcodeit:
{% endblocktrans %}
{{ request.scheme }}://{{ domain }}{% url 'user_account:activate' uid=uid token=token %}
{% endautoescape %}

apps/user_account/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ activation_message }}

</body>
</html>

apps/user_account/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Social Login</title>
</head>
<body>

<button onclick="signup_form()">Signup form</button>
<button onclick="login_form()">Login form</button>

<form id="signup-form" method="post" action="" enctype="multipart/form-data" hidden >
    {% csrf_token %}
    {{ signup_form }}
    <input type="submit" value="submit">
</form>


<form id="login-form" method="post" action=""  hidden>
    {% csrf_token %}
    {{ login_form }}
    <input type="submit" value="submit">
</form>


<a href="{% url 'social:begin' 'google-oauth2' %}">Google Login</a>

<a href="{% url 'social:begin' 'facebook' %}">Facebook Login</a>


<script type="text/javascript">
    function signup_form() {
        var element = document.getElementById('signup-form');
        if (element.hidden===true){
        element.hidden = false;
        }
        else {
            element.hidden = true;
        }

    }

    function login_form() {
    var element = document.getElementById('login-form');
    if (element.hidden===true){
    element.hidden = false;
    }
    else {
        element.hidden = true;
    }

}

</script>

</body>
</html>

apps/user_account/templates/logout_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>


<form hidden="T">
    <div id="signup_form"></div>

</form>

<form></form>

</body>
</html>

apps/user_account/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>

Testins
<button id="test" type="button" >test button</button>

<script type="text/javascript">
    function do_this() {
            console.log('done')

    }

        $('#test').click({do_this()})
</script>

</body>
</html>